import {
  DEFAULT_BRANCH_ID,
  DEFAULT_BRANCH_NAME,
  type AssetRecord,
  type AttendanceRecord,
  type BranchRecord,
  type EmployeeRecord,
  type MenuRecord,
  type OrderRecord,
  type RatingRecord,
  type StockHistoryRecord,
  type SupplyRecord,
} from "@/lib/models";

const createdAt = "2026-04-07T00:00:00.000Z";

export const branchSeedData: BranchRecord[] = [
  {
    id: DEFAULT_BRANCH_ID,
    name: DEFAULT_BRANCH_NAME,
    address: "Jl. Jenderal Sudirman No. 88, Pekanbaru",
    manager: "Salsa Putri",
    phoneNumber: "0761-334455",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "branch-2",
    name: "CafeFlow Jakarta",
    address: "Jl. Kemang Raya No. 12, Jakarta Selatan",
    manager: "Rizky Pratama",
    phoneNumber: "021-778899",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "branch-3",
    name: "CafeFlow Bandung",
    address: "Jl. Braga No. 24, Bandung",
    manager: "Nadia Lestari",
    phoneNumber: "022-556677",
    createdAt,
    updatedAt: createdAt,
  },
];

export const supplySeedData: SupplyRecord[] = [
  {
    id: "supply-1",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    materialName: "Coffee Beans",
    supplier: "Kopi Gayo Nusantara",
    stockQuantity: 4,
    unit: "kg",
    purchasePrice: 185000,
    lastRestockDate: "2026-04-03",
    lowStockThreshold: 1.5,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "supply-2",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    materialName: "Fresh Milk",
    supplier: "Green Dairy",
    stockQuantity: 12,
    unit: "liter",
    purchasePrice: 22000,
    lastRestockDate: "2026-04-05",
    lowStockThreshold: 3,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "supply-3",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    materialName: "Palm Sugar",
    supplier: "Sweet Roots",
    stockQuantity: 3.5,
    unit: "kg",
    purchasePrice: 42000,
    lastRestockDate: "2026-04-04",
    lowStockThreshold: 1,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "supply-4",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    materialName: "Butter Croissant",
    supplier: "Atelier Bakery",
    stockQuantity: 26,
    unit: "pcs",
    purchasePrice: 12000,
    lastRestockDate: "2026-04-06",
    lowStockThreshold: 10,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "supply-5",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    materialName: "Matcha Powder",
    supplier: "Uji Green",
    stockQuantity: 1.8,
    unit: "kg",
    purchasePrice: 360000,
    lastRestockDate: "2026-04-02",
    lowStockThreshold: 0.7,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "supply-6",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    materialName: "Fresh Pasta",
    supplier: "Pasta Lab",
    stockQuantity: 22,
    unit: "pcs",
    purchasePrice: 9000,
    lastRestockDate: "2026-04-06",
    lowStockThreshold: 8,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "supply-7",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    materialName: "Cream Cheese",
    supplier: "Daily Churn",
    stockQuantity: 2.4,
    unit: "kg",
    purchasePrice: 118000,
    lastRestockDate: "2026-04-05",
    lowStockThreshold: 1,
    createdAt,
    updatedAt: createdAt,
  },
];

export const menuSeedData: MenuRecord[] = [
  {
    id: "menu-1",
    slug: "es-kopi-susu-aren",
    name: "Es Kopi Susu Aren",
    category: "Coffee",
    description: "Espresso creamy dengan susu segar dan manis karamel dari gula aren.",
    image:
      "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=1400&q=80",
    stock: 58,
    status: "Aktif",
    story: "Minuman signature yang seimbang, ringan, dan jadi favorit untuk jam sibuk pagi hingga sore.",
    price: 28000,
    rating: 4.9,
    prepTime: "6 min",
    pairing: "Paling cocok dengan butter croissant hangat.",
    ingredients: ["Coffee Beans", "Fresh Milk", "Palm Sugar"],
    recipe: [
      {
        id: "recipe-1",
        supplyId: "supply-1",
        ingredientName: "Coffee Beans",
        quantity: 18,
        usageUnit: "g",
      },
      {
        id: "recipe-2",
        supplyId: "supply-2",
        ingredientName: "Fresh Milk",
        quantity: 180,
        usageUnit: "ml",
      },
      {
        id: "recipe-3",
        supplyId: "supply-3",
        ingredientName: "Palm Sugar",
        quantity: 20,
        usageUnit: "g",
      },
    ],
    featured: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "menu-2",
    slug: "croissant-butter",
    name: "Croissant Butter",
    category: "Dessert",
    description: "Pastry berlapis yang renyah di luar dan lembut di bagian tengah.",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1400&q=80",
    stock: 21,
    status: "Promo",
    story: "Dipanggang fresh setiap pagi untuk menemani kopi dengan tekstur flaky yang ringan.",
    price: 24000,
    rating: 4.8,
    prepTime: "4 min",
    pairing: "Nikmat dipadukan dengan long black atau cappuccino.",
    ingredients: ["Butter Croissant"],
    recipe: [
      {
        id: "recipe-4",
        supplyId: "supply-4",
        ingredientName: "Butter Croissant",
        quantity: 1,
        usageUnit: "pcs",
      },
    ],
    featured: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "menu-3",
    slug: "matcha-cream-latte",
    name: "Matcha Cream Latte",
    category: "Drink",
    description: "Latte matcha creamy dengan finish manis yang lembut dan earthy.",
    image:
      "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=1400&q=80",
    stock: 16,
    status: "Aktif",
    story: "Pilihan non-coffee premium dengan foam halus dan warna hijau yang clean.",
    price: 32000,
    rating: 4.8,
    prepTime: "5 min",
    pairing: "Enak dinikmati bersama honey toast atau lemon cake.",
    ingredients: ["Matcha Powder", "Fresh Milk"],
    recipe: [
      {
        id: "recipe-5",
        supplyId: "supply-5",
        ingredientName: "Matcha Powder",
        quantity: 12,
        usageUnit: "g",
      },
      {
        id: "recipe-6",
        supplyId: "supply-2",
        ingredientName: "Fresh Milk",
        quantity: 200,
        usageUnit: "ml",
      },
    ],
    featured: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "menu-4",
    slug: "truffle-cream-pasta",
    name: "Truffle Cream Pasta",
    category: "Food",
    description: "Pasta creamy dengan aroma truffle yang kaya dan plating modern.",
    image:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1400&q=80",
    stock: 12,
    status: "Spesial",
    story: "Menu comfort food untuk lunch crowd dengan rasa gurih, creamy, dan terasa premium.",
    price: 54000,
    rating: 4.7,
    prepTime: "12 min",
    pairing: "Pasangkan dengan sparkling yuzu tea untuk rasa yang lebih segar.",
    ingredients: ["Fresh Pasta", "Fresh Milk"],
    recipe: [
      {
        id: "recipe-7",
        supplyId: "supply-6",
        ingredientName: "Fresh Pasta",
        quantity: 1,
        usageUnit: "pcs",
      },
      {
        id: "recipe-8",
        supplyId: "supply-2",
        ingredientName: "Fresh Milk",
        quantity: 150,
        usageUnit: "ml",
      },
    ],
    featured: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "menu-5",
    slug: "smoked-beef-sando",
    name: "Smoked Beef Sando",
    category: "Food",
    description: "Roti lembut dengan smoked beef, mustard mayo, dan acar segar.",
    image:
      "https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&w=1400&q=80",
    stock: 18,
    status: "Aktif",
    story: "Menu brunch cepat saji yang tetap nyaman untuk dine-in maupun takeaway.",
    price: 42000,
    rating: 4.8,
    prepTime: "8 min",
    pairing: "Cocok dengan iced americano atau peach tea.",
    ingredients: ["Fresh Milk"],
    recipe: [
      {
        id: "recipe-9",
        supplyId: "supply-2",
        ingredientName: "Fresh Milk",
        quantity: 60,
        usageUnit: "ml",
      },
    ],
    featured: false,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "menu-6",
    slug: "caramel-sea-salt-cheesecake",
    name: "Caramel Sea Salt Cheesecake",
    category: "Dessert",
    description: "Cheesecake lembut dengan caramel glaze dan sentuhan sea salt.",
    image:
      "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=1400&q=80",
    stock: 14,
    status: "Aktif",
    story: "Dessert signature untuk penutup yang manis, creamy, dan tetap seimbang.",
    price: 36000,
    rating: 4.9,
    prepTime: "3 min",
    pairing: "Paling pas dengan espresso atau dirty latte.",
    ingredients: ["Cream Cheese"],
    recipe: [
      {
        id: "recipe-10",
        supplyId: "supply-7",
        ingredientName: "Cream Cheese",
        quantity: 120,
        usageUnit: "g",
      },
    ],
    featured: false,
    createdAt,
    updatedAt: createdAt,
  },
];

export const employeeSeedData: EmployeeRecord[] = [
  {
    id: "employee-1",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    employeeName: "Ayu Maharani",
    position: "Barista",
    phoneNumber: "081234567890",
    email: "ayu@cafeflow.id",
    photo:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=80",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "employee-2",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    employeeName: "Rizal Hidayat",
    position: "Cashier",
    phoneNumber: "081298765432",
    email: "rizal@cafeflow.id",
    photo:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=80",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "employee-3",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    employeeName: "Salsa Putri",
    position: "Manager",
    phoneNumber: "081223344556",
    email: "salsa@cafeflow.id",
    photo:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=1200&q=80",
    createdAt,
    updatedAt: createdAt,
  },
];

export const assetSeedData: AssetRecord[] = [
  {
    id: "asset-1",
    assetName: "Mesin Espresso La Marzocco",
    category: "Machine",
    purchaseDate: "2025-08-10",
    purchasePrice: 85000000,
    condition: "Good",
    photo:
      "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=1200&q=80",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "asset-2",
    assetName: "Set Kursi Kayu Oak",
    category: "Furniture",
    purchaseDate: "2025-06-14",
    purchasePrice: 12500000,
    condition: "Maintenance",
    photo:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "asset-3",
    assetName: "POS Tablet Front Counter",
    category: "Equipment",
    purchaseDate: "2025-10-01",
    purchasePrice: 7800000,
    condition: "Good",
    photo:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    createdAt,
    updatedAt: createdAt,
  },
];

export const orderSeedData: OrderRecord[] = [
  {
    id: "order-1",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    orderCode: "INV-CAFE-042",
    customerName: "Kartika",
    tableNumber: "Meja 07",
    status: "Dapur",
    paymentMethod: "QRIS",
    items: [
      {
        id: "order-item-1",
        menuId: "menu-1",
        menuName: "Es Kopi Susu Aren",
        quantity: 2,
        unitPrice: 28000,
      },
      {
        id: "order-item-2",
        menuId: "menu-2",
        menuName: "Croissant Butter",
        quantity: 1,
        unitPrice: 24000,
      },
    ],
    notes: "Less ice untuk kopi.",
    subtotal: 80000,
    serviceFee: 6000,
    total: 86000,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "order-2",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    orderCode: "INV-CAFE-043",
    customerName: "Yoga",
    tableNumber: "Meja 03",
    status: "Pramusaji",
    paymentMethod: "Cash",
    items: [
      {
        id: "order-item-3",
        menuId: "menu-3",
        menuName: "Matcha Cream Latte",
        quantity: 2,
        unitPrice: 32000,
      },
    ],
    notes: "Pickup 10 menit lagi.",
    subtotal: 64000,
    serviceFee: 6000,
    total: 70000,
    createdAt,
    updatedAt: createdAt,
  },
];

export const ratingSeedData: RatingRecord[] = [
  {
    id: "rating-1",
    customerName: "Kartika",
    serviceRating: 5,
    foodRating: 4,
    comment: "Pelayanannya ramah dan kopinya enak. Akan balik lagi.",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rating-2",
    customerName: "Bima",
    serviceRating: 4,
    foodRating: 5,
    comment: "Makanan datang cepat dan rasanya mantap.",
    createdAt,
    updatedAt: createdAt,
  },
];

export const stockHistorySeedData: StockHistoryRecord[] = [
  {
    id: "history-1",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    supplyId: "supply-2",
    materialName: "Fresh Milk",
    changeType: "Order",
    quantityChanged: -400,
    unit: "ml",
    resultingStock: 11.6,
    supplyUnit: "liter",
    date: createdAt,
    reference: "INV-CAFE-042",
  },
  {
    id: "history-2",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    supplyId: "supply-1",
    materialName: "Coffee Beans",
    changeType: "Order",
    quantityChanged: -36,
    unit: "g",
    resultingStock: 3.964,
    supplyUnit: "kg",
    date: createdAt,
    reference: "INV-CAFE-042",
  },
  {
    id: "history-3",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    supplyId: "supply-2",
    materialName: "Fresh Milk",
    changeType: "Restock",
    quantityChanged: 4,
    unit: "liter",
    resultingStock: 12,
    supplyUnit: "liter",
    date: "2026-04-05T09:15:00.000Z",
    reference: "Restock supplier",
  },
];

export const attendanceSeedData: AttendanceRecord[] = [
  {
    id: "attendance-1",
    employeeId: "employee-1",
    employeeName: "Ayu Maharani",
    position: "Barista",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    date: "2026-04-07",
    checkIn: "2026-04-07T08:05:00.000Z",
    checkOut: "2026-04-07T17:10:00.000Z",
    totalWorkingHours: 9.08,
    method: "Manual",
    isLate: false,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "attendance-2",
    employeeId: "employee-2",
    employeeName: "Rizal Hidayat",
    position: "Cashier",
    branchId: DEFAULT_BRANCH_ID,
    branchName: DEFAULT_BRANCH_NAME,
    date: "2026-04-07",
    checkIn: "2026-04-07T08:18:00.000Z",
    checkOut: "2026-04-07T17:02:00.000Z",
    totalWorkingHours: 8.73,
    method: "QR Attendance",
    isLate: true,
    createdAt,
    updatedAt: createdAt,
  },
];

export const cafeStats = [
  { label: "Signature drinks", value: "24 menu" },
  { label: "Pickup tercepat", value: "12 menit" },
  { label: "Happy customer", value: "4.9/5" },
];

export const serviceHighlights = [
  {
    title: "Freshly brewed all day",
    label: "Daily roast",
    description: "House blend roasted mingguan untuk rasa yang stabil dari pagi sampai closing.",
  },
  {
    title: "Mobile order yang praktis",
    label: "Pickup ready",
    description: "Pelanggan bisa lihat menu, pilih item, dan check out dengan alur yang nyaman di layar kecil.",
  },
  {
    title: "POS dan operasional dalam satu sistem",
    label: "Cafe OS",
    description: "Dashboard admin tetap lengkap untuk menu, stok, staff, laporan, dan pemantauan order.",
  },
];

export const menuCategories = [
  {
    title: "Coffee",
    itemCount: "12 items",
    description: "Espresso-based, manual brew, dan signature latte hangat.",
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Food",
    itemCount: "9 items",
    description: "Brunch plates, toast, pasta, dan comfort bites untuk dine-in.",
    image:
      "https://images.unsplash.com/photo-1521305916504-4a1121188589?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Dessert",
    itemCount: "8 items",
    description: "Pastry buttery, cake slice lembut, dan dessert seasonal.",
    image:
      "https://images.unsplash.com/photo-1483695028939-5bb13f8648b0?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Drink",
    itemCount: "10 items",
    description: "Mocktail, sparkling tea, dan minuman non-coffee yang ringan.",
    image:
      "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=80",
  },
];

export const testimonials = [
  {
    name: "Kartika Pramesti",
    role: "Remote Designer",
    quote: "Suasana brand-nya terasa premium, dan ordering flow di mobile jauh lebih enak dipakai.",
  },
  {
    name: "Raka Surya",
    role: "Weekend Regular",
    quote: "Menu favorit jadi mudah ditemukan, tampilannya bikin lapar, dan checkout-nya terasa ringan.",
  },
  {
    name: "Alya Fitrani",
    role: "Community Host",
    quote: "Admin dashboard tetap lengkap, tapi sisi customer sekarang terasa seperti aplikasi cafe modern.",
  },
];

export const summaryCards = [
  {
    title: "Revenue Hari Ini",
    value: "Rp 8,4 Jt",
    change: "+18% dari kemarin",
    detail: "124 transaksi selesai",
    tone: "from-[#ead8c4] via-[#fff9f4] to-[#f7ece0]",
  },
  {
    title: "Pesanan Aktif",
    value: "42",
    change: "9 order menunggu pickup",
    detail: "Rata-rata 7 menit per order",
    tone: "from-[#f3e7d9] via-[#fff9f2] to-[#f4efe7]",
  },
  {
    title: "Stok Menipis",
    value: "7 item",
    change: "2 item kritis hari ini",
    detail: "Arabika blend dan susu oat",
    tone: "from-[#e5d5c1] via-[#fff7ee] to-[#f6ede4]",
  },
  {
    title: "Rating Staff",
    value: "4.8/5",
    change: "Skor pelayanan stabil",
    detail: "Ayu memimpin CSAT minggu ini",
    tone: "from-[#efe4d8] via-[#fffaf5] to-[#f2e8de]",
  },
];

export const salesSeries = [
  { day: "Sen", profit: 2400000, loss: 400000 },
  { day: "Sel", profit: 3100000, loss: 520000 },
  { day: "Rab", profit: 2900000, loss: 430000 },
  { day: "Kam", profit: 3800000, loss: 610000 },
  { day: "Jum", profit: 4600000, loss: 720000 },
  { day: "Sab", profit: 5200000, loss: 800000 },
  { day: "Min", profit: 4100000, loss: 560000 },
];

export const orderFlow = [
  {
    table: "Meja 03",
    customer: "Kartika",
    items: 3,
    status: "Pramusaji",
    eta: "2 menit",
  },
  {
    table: "Meja 07",
    customer: "Yoga",
    items: 4,
    status: "Dapur",
    eta: "9 menit",
  },
  {
    table: "Meja 12",
    customer: "Raka",
    items: 2,
    status: "Siap Antar",
    eta: "1 menit",
  },
  {
    table: "Takeaway",
    customer: "Luna",
    items: 5,
    status: "Selesai",
    eta: "Pickup",
  },
];

export const specialMenus = [
  {
    title: "Ramadan Iftar Set",
    schedule: "Setiap 17.00 - 20.00",
    discount: "15%",
  },
  {
    title: "Friday Jazz Night",
    schedule: "Jumat malam",
    discount: "Buy 2 Get 1",
  },
  {
    title: "Morning Matcha Club",
    schedule: "Senin - Kamis, 08.00 - 11.00",
    discount: "Free upsize",
  },
];

export const inventoryAlerts = [
  { item: "Coffee Beans", remaining: "4 kg", supplier: "Kopi Gayo Nusantara" },
  { item: "Fresh Milk", remaining: "12 liter", supplier: "Green Dairy" },
  { item: "Butter Croissant", remaining: "26 pcs", supplier: "Atelier Bakery" },
];

export const staffOverview = [
  { name: "Ayu", role: "Pramusaji", attendance: "98%", score: "4.9" },
  { name: "Rizal", role: "Barista", attendance: "96%", score: "4.8" },
  { name: "Salsa", role: "Kasir", attendance: "95%", score: "4.7" },
];
